FROM php:fpm

RUN apt-get update -y
RUN apt-get install -y libzip-dev libpng-dev
RUN docker-php-ext-install pdo pdo_mysql gd zip

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer