version: '3.9'
networks:
  laradock:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - node
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laradock

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    tty: true
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - laradock

  node:
    image: node:alpine
    container_name: node
    ports:
      - 5173:5173
    working_dir: /var/www/html
    tty: true
    volumes:
      - ./src:/var/www/html
    networks:
      - laradock

  php:
    container_name: php
    working_dir: /var/www/html
    build:
      context: ./docker/php
      dockerfile: dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
    networks:
      - laradock

  cron:
    container_name: cron
    build:
      context: ./docker/cron
      dockerfile: dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - laradock